cassandra:
  hostname: cassandra
  image: sparkoin/cassandra:5
  domainname: loc
  expose:
   - "9042"
   - "9160"
   - "8080"
  ports:
    - "8180:8080"
    - "9160:9160"
    - "9042:9042"
  environment:
    JAVA_OPTS: -Ddefault.host=cassandra:9160 -Dfile.encoding=UTF8
    CQLSH_HOST: cassandra
  restart: always
  volumes:
    - cassandra:/app/data/cassandra

bitcore:
  hostname: bitcore
  domainname: loc
  image: sparkoin/bitcore:5
  links:
   - "cassandra:cassandra.loc"
  restart: always
  volumes: 
    - "bitcore:/app/data/bitcore" 
  environment:
    BITCOIN_NETWORK: livenet 
  ports: [ "5858:5858", "3001:3001" ]

jupyter:
  hostname: jupyter
  domainname: loc
  image: sparkoin/jupyter:5
  ports:
    - "8888:8888"
  links:
    - "cassandra:cassandra.loc"


