shared:
  hostname: shared
  image: sparkoin/shared:1
  volumes:
     - "./shared:/app/shared"

spark0:
  hostname: spark0 
  extends:
    file: services/spark.yml
    service: spark-master 
  ports:
    - "8180:8080"
  links:
    - "cassandra0:cassandra.loc"
    - "kafka0:zookeper.loc"
    - "kafka1:kafka.loc"
  restart: always
  volumes_from: [ "shared" ]
   
kafka0:
  hostname: kafka0
  extends:
    file: services/kafka.yml
    service: zookeeper
  restart: always
  volumes_from: [ "shared" ]

kafka1:
  hostname: kafka1
  links:
    - "kafka0:zookeeper.loc"
  extends:
    file: services/kafka.yml
    service: kafka
  restart: always
  volumes_from: [ "shared" ]

cassandra0:
  hostname: cassandra0
  extends:
    file: services/cassandra.yml
    service: cassandra
  ports:
    - "8080:8080"
    - "9160:9160"
    - "9042:9042"
  environment:
    JAVA_OPTS: -Ddefault.host=cassandra0:9160 -Dfile.encoding=UTF8
    CQLSH_HOST: cassandra0
    PS1: "\\u@\\h:\\w\\$$ "
  restart: always
  volumes_from: [ "shared" ]

bitcore:
  hostname: bitcore
  domainname: loc
  image: sparkoin/bitcore:1
  links:
   - "kafka0:zookeeper.loc"
  restart: always
  volumes:
    - "./services/bitcore/server.js:/app/server.js"
  volumes_from: [ "shared" ]

zeppelin:
  hostname: zeppelin
  extends:
    file: services/zeppelin.yml
    service: zeppelin
  links:
    - "spark0:spark-master.loc"
    - "cassandra0:cassandra.loc"
    - "kafka0:zookeper.loc"
    - "kafka1:kafka.loc"
  volumes:
   - "./notebook:/app/zeppelin/notebook"
  volumes_from: [ "shared" ]


