spark0:
  hostname: spark0 
  extends:
    file: services/spark.yml
    service: spark-master 
  ports:
    - "8180:8080"

kafka0:
  hostname: kafka0
  extends:
    file: services/kafka.yml
    service: zookeeper

kafka1:
  hostname: kafka1
  links:
    - "kafka0:zookeeper.loc"
  extends:
    file: services/kafka.yml
    service: kafka

cassandra0:
  hostname: cassandra0
  extends:
    file: services/cassandra.yml
    service: cassandra
  ports:
    - "8080:8080"
    - "9160:9160"
    - "9042:9042"
  environment:
    JAVA_OPTS: -Ddefault.host=cassandra0:9160

zeppelin:
  hostname: zeppelin
  extends:
    file: services/zeppelin.yml
    service: zeppelin
  links:
    - "spark0:spark-master.loc"
    - "cassandra0:cassandra.loc"
    - "kafka0:zookeper.loc"
    - "kafka1:kafka.loc"
  volumes:
   - "./notebook:/app/zeppelin/notebook"


