spark0:
  hostname: spark0 
  extends:
    file: services/spark.yml
    service: spark-master 

#spark1:
#  hostname: spark1
#  extends:
#    file: services/spark.yml
#    service: spark-slave
#  links:
#    - "spark0:spark-master.loc"

kafka0:
  hostname: kafka0
  extends:
    file: services/kafka.yml
    service: zookeeper

kafka1:
  hostname: kafka1
  links:
    - "kafka0:zookeeper.loc"
  extends:
    file: services/kafka.yml
    service: kafka

cassandra0:
  hostname: cassandra0
  extends:
    file: services/cassandra.yml
    service: cassandra

zeppelin:
  hostname: zeppelin
  extends: 
    file: services/zeppelin.yml
    service: zeppelin
  links: 
    - "spark0:spark-master.loc"
    - "cassandra0:cassandra.loc"
    - "kafka0:zookeper.loc"
    - "kafka1:kafka.loc"
  volumes:
    - "./notebook:/app/zeppelin/notebook"
  ports:
    - "80:8080"
