shared:
  hostname: shared
  image: sparkoin/shared:2
  volumes:
     - "./apps:/app/apps"
     - "./apps/etc/notebook:/app/zeppelin/notebook"

zookeeper:
  hostname: zookeeper
  domainname: loc
  image: sparkoin/kafka:2
  command: bash zookeper.sh
  ports:
    - "2181:2181"
  restart: always
  volumes_from: [ "shared" ]

kafka:
  hostname: kafka
  domainname: loc
  image: sparkoin/kafka:2
  command: bash kafka.sh
  links:
    - "zookeeper:zookeeper.loc"
  expose:
    - 9092
  ports:
    - "9092:9092"
  restart: always
  volumes_from: [ "shared" ]

bitcore:
  hostname: bitcore
  domainname: loc
  image: sparkoin/bitcore:2
  links:
   - "zookeeper:zookeeper.loc"
   - "kafka:kafka.loc"
  restart: always
  volumes_from: [ "shared" ]

spark:
  hostname: spark
  domainname: loc
  image: sparkoin/spark:2
  ports:
    - "8180:8080"
    - "7077:7077"
  command: bash master.sh
  links:
    - "cassandra:cassandra.loc"
    - "zookeeper:zookeper.loc"
    - "kafka:kafka.loc"
  restart: always
  volumes_from: [ "shared" ]

cassandra:
  hostname: cassandra
  image: sparkoin/cassandra:2
  domainname: loc
  expose:
   - "9042"
   - "9160"
   - "8080"
  ports:
    - "8080:8080"
    - "9160:9160"
    - "9042:9042"
  environment:
    JAVA_OPTS: -Ddefault.host=cassandra:9160 -Dfile.encoding=UTF8
    CQLSH_HOST: cassandra
  restart: always
  volumes_from: [ "shared" ]

zeppelin:
  hostname: zeppelin
  domainname: loc
  image: sparkoin/zeppelin:2
  ports:
    - "80:8080"
  volumes_from: [ "shared" ]
  links:
    - "spark:spark.loc"
    - "cassandra:cassandra.loc"
    - "zookeeper:zookeper.loc"
    - "kafka:kafka.loc"
  command: bash zeppelin.sh
