shared:
  hostname: shared
  image: sparkoin/shared:2
  volumes:
     - "./notebook:/app/zeppelin/notebook"
     - "./apps:/app/apps"

spark0:
  hostname: spark0 
  image: sparkoin/spark:2
  domainname: loc
  ports:
    - "8180:8080"
    - "7077:7077"
  command: bash master.sh
  links:
    - "cassandra0:cassandra.loc"
    - "kafka0:zookeper.loc"
    - "kafka1:kafka.loc"
  restart: always
  volumes_from: [ "shared" ]
   
kafka0:
  hostname: kafka0
  image: sparkoin/kafka:2
  command: bash zookeper.sh
  domainname: loc
  ports:
    - "2181:2181"
  restart: always
  volumes_from: [ "shared" ]

kafka1:
  hostname: kafka1
  domainname: loc
  image: sparkoin/kafka:2
  command: bash kafka.sh
  links:
    - "kafka0:zookeeper.loc"
  ports:
    - "9092:9092"
  restart: always
  volumes_from: [ "shared" ]

cassandra0:
  hostname: cassandra0
  image: sparkoin/cassandra:2
  domainname: loc
  expose:
   - "9042"
   - "9160"
   - "8080"
  ports:
    - "8080:8080"
    - "9160:9160"
    - "9042:9042"
  environment:
    JAVA_OPTS: -Ddefault.host=cassandra0:9160 -Dfile.encoding=UTF8
    CQLSH_HOST: cassandra0
  restart: always
  volumes_from: [ "shared" ]

bitcore:
  hostname: bitcore
  domainname: loc
  image: sparkoin/bitcore:2
  links:
   - "kafka0:zookeeper.loc"
  restart: always
  volumes:
    - "./services/bitcore/server.js:/app/server.js"
  environment:
    BITCOIN_NETWORK: livenet
  volumes_from: [ "shared" ]

zeppelin:
  hostname: zeppelin
  image: sparkoin/zeppelin:2
  domainname: loc
  command: bash zeppelin.sh
  ports:
    - "80:8080"
  links:
    - "spark0:spark-master.loc"
    - "cassandra0:cassandra.loc"
    - "kafka0:zookeper.loc"
    - "kafka1:kafka.loc"
  volumes_from: [ "shared" ]

