hadoop:
  hostname: hadoop
  domainname: loc
  image: sparkoin/hadoop:4
  volumes:
    - "hadoop:/app/data/hadoop"
  ports: [ "8020:8020" ]

bitcore:
  hostname: bitcore
  domainname: loc
  image: sparkoin/bitcore:4
  links:
   - "hadoop:hadoop.loc"
  restart: always
  volumes: 
    - "./apps/bitcore:/app/apps/bitcore"
    - "bitcore:/app/data/bitcore" 
  environment:
    BITCOIN_NETWORK: livenet 
  ports: [ "5858:5858", "3001:3001" ]

jupyter:
  hostname: jupyter
  domainname: loc
  image: sparkoin/jupyter:4
  ports:
    - "8888:8888"
  links:
    - "hadoop:hadoop.loc"
  volumes:
    - "bitcore:/app/data/bitcore" 
    - "./apps/jupyter:/app/apps/jupyter"
    - "./apps/sparkoin:/app/apps/sparkoin"

redis:
  hostname: redis
  domainname: loc
  image: sparkoin/redis:4
  ports:
   - "6379:6379"
  volumes:
   - "redis:/app/data/redis"
