cassandra:
  hostname: cassandra
  image: sparkoin/cassandra:4
  domainname: loc
  expose:
   - "9042"
   - "9160"
   - "8080"
  ports:
    - "8180:8080"
    - "9160:9160"
    - "9042:9042"
  environment:
    JAVA_OPTS: -Ddefault.host=cassandra:9160 -Dfile.encoding=UTF8
    CQLSH_HOST: cassandra
  restart: always
  volumes:
    - cassandra:/app/data/cassandra
    - ./apps/cassandra:/app/apps/cassandra

bitcore:
  hostname: bitcore
  domainname: loc
  image: sparkoin/bitcore:4
  links:
   - "cassandra:cassandra.loc"
  restart: always
  volumes: 
    - "./apps/bitcore:/app/apps/bitcore"
    - "bitcore:/app/data/bitcore" 
  environment:
    BITCOIN_NETWORK: livenet 
  ports: [ "5858:5858", "3001:3001" ]

jupyter:
  hostname: jupyter
  domainname: loc
  image: sparkoin/jupyter:4
  ports:
    - "8888:8888"
  links:
    - "cassandra:cassandra.loc"
  volumes:
    - "./apps/jupyter:/app/apps/jupyter"
    - "./apps/sparkoin:/app/apps/sparkoin"


