hadoop:
  hostname: hadoop
  domainname: loc
  image: sparkoin/hadoop:1
  volumes:
    - "hadoop:/app/data/hadoop"
  ports: [ "8020:8020" ]

bitcore:
  hostname: bitcore
  domainname: loc
  image: sparkoin/bitcore:3
  links:
   - "hadoop:hadoop.loc"
  restart: always
  volumes: 
    - "./apps/bitcore:/app/apps/bitcore"
    - "bitcore:/app/data/bitcore" 
  environment:
    BITCOIN_NETWORK: livenet 
    #BITCORE_STOP_AT: 1000
  ports: [ "5858:5858", "3001:3001" ]

jupyter:
  hostname: jupyter
  domainname: loc
  image: sparkoin/jupyter:4
  ports:
    - "8888:8888"
  links:
    - "hadoop:hadoop.loc"
  volumes:
    - "./apps/jupyter:/app/apps/jupyter"
    - "./apps/sparkoin:/app/apps/sparkoin"
