FROM sparkoin/java:4
WORKDIR /app
RUN wget http://www-eu.apache.org/dist/incubator/zeppelin/0.5.6-incubating/zeppelin-0.5.6-incubating-bin-all.tgz 
RUN wget http://central.maven.org/maven2/com/google/guava/guava/14.0.1/guava-14.0.1.jar 
