alias dk=docker
alias dkc=docker-compose
alias dki="docker images"

function dke {
  x=$(docker ps | grep $1 | awk '{ print $1 }')
  docker exec -u=0 -ti $x /bin/sh
}

function dkr {
  x=$(docker images | grep $1 | head -1 | awk '{ print $3 }')
  docker run -ti -u=0 $x /bin/bash
}

function dkb {
 docker build -t $DOCKER_MACHINE_NAME/$1 $1
} 


alias u="cd .. ; ls"
alias uu="cd ../.. ; ls"
alias ll="ls -l"

alias gst="git status"
alias gad="git add"
alias gca="git commit -a -m"
alias gpo="git push origin"
alias gbr="git branch -a"

